FORMAT: 1A
HOST: http://api.factory.zone/v1/

# Factory - Feature-KPI

KPI feature enables the organization track employee KPI information in line with Organizational goals with a periodd.

# KPI Category Collection [/kpi-categories]

## List KPI Categories [GET]
+ Response 200 (application/json)

        [
            {
                "id": "1";
                "name": "Human Resources";
                "description": "KPI on employee related activities";
                "user_id": 1;
                "org_id":1;
                "created_at": "2017-02-10 20:40:52";
                "modified_at": "2017-02-10 20:40:52";
                
            }
            {
                "id": "2";
                "name": "Projects";
                "description": "KPI on employee related activities";
                "user_id": 1;
                "org_id":1;
                 "created_at": "2017-02-10 20:40:52";
                "modified_at": "2017-02-10 20:40:52";
                
            }
        
        ]

### Add Category [PUT]

+ Request (application/json)

            {
                "name": "Projects";
                "description": "KPI on employee related activities";
                "user_id": 1;
                "org_id":1;
            }

+ Response 201 (application/json)

    + Headers

            Location: /kpi/:id

    + Body

            {
                "id": "2";
                "name": "Projects";
                "description": "KPI on employee related activities";
                "user_id": 1;
                "org_id":1;
                 "created_at": "2017-02-10 20:40:52";
                "modified_at": "2017-02-10 20:40:52";
                
            }
            

## Manage KPI Category [/kpi-category/{id}]

 + Parameters
 
    + id - KPI Category ID form of an integer

### View Category [GET]

+ Response 200 (application/json)

   `
    + Headers
        
            Location: /kpi-category/:id

    + Body
        
            {
                "id": "1";
                "name": "Human Resources";
                "description": "KPI on employee related activities";
                "user_id": 1;
                "org_id":1;
                "created_at": "2017-02-10 20:40:52";
                "modified_at": "2017-02-10 20:40:52";
            }
### Edit Category [PUT]

+ Request (application/json)

         {
                "name": "Projects";
                "description": "KPI on employee related activities";
                "user_id": 1;
                "org_id":1;
            }

+ Response 201 (application/json)

    + Headers

            Location: /kpi/:id

    + Body

            {
                "id": "2";
                "name": "Projects";
                "description": "KPI on employee related activities";
                "user_id": 1;
                "org_id":1;
                 "created_at": "2017-02-10 20:40:52";
                "modified_at": "2017-02-10 20:40:52";
                
            }
            
### Remove Category [DELETE]

+ Response 200 (application/json)

    + Body
    
            {
                "status": "Success";
                "message": "KPI Category was succesfully deleted";
            }

# KPI Collection [/kpis]

### List KPI [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1;
                "title": "Sales";
                "frequency": "Daily";
                "format": "Number";
                "target": "30000";
                "category_id": 1;
                "org_id": 1;
                "user_id": 23;
                "status": 1;
                "created_at": "2017-02-11 20:40:52";
                "modified_at": "2017-02-11 20:40:52";
            }
            
            {
                "id": 2;
                "title": "Total Sales";
                "frequency": "Weekly";
                "format": "Number";
                "target": "250000";
                "category_id": 1;
                "org_id": 1;
                "user_id": 23;
                "status": 0;
                "created_at": "2017-02-11 20:40:52";
                "modified_at": "2017-02-11 20:40:52";
            }
            {
                "id": 3;
                "title": "Attendance";
                "frequency": "Monthly";
                "format": "Number";
                "target": "24";
                "category_id": 2;
                "org_id": 1;
                "user_id": 23;
                "status": 1;
                "created_at": "2017-02-11 20:40:52";
                "modified_at": "2017-02-11 20:40:52";
            }
        ]


### Add KPI [POST]

+ Request (application/json)

         {

                "title": "Number of Completed Tasks";
                "description": "KPI tracking tasks completed by users";
                "frequency": "Weekly";
                "format": "Number";
                "target": "3";
                "category_id": 1;
                "org_id": 1;
                "user_id": 23;
                "status": 1;
            }

+ Response 201 (application/json)

    + Headers

            Location: /kpi/:id

    + Body

            {
                "id": 2;
                "title": "Number of Completed Tasks";
                "frequency": "Weekly";
                "format": "Number";
                "target": "3";
                "category_id": 1;
                "org_id": 1;
                "user_id": 23;
                "status": 1;
                "created_at": "2017-02-11 20:40:52";
                "modified_at": "2017-02-11 20:40:52";
            }
            
## Manage KPI [/kpis/{id}]

 + Parameters
 
    + id - KPI ID form of an integer

### View KPI Details [GET]

+ Response 200 (application/json)

   `
    + Headers
        
            Location: /kpi/:id

    + Body
        
            {
                "id": 1;
                "title": "Sales";
                "frequency": "Daily";
                "format": "Number";
                "target": "30000";
                "category_id": 1;
                "org_id": 1;
                "user_id": 23;
                "status": 1;
                "created_at": "2017-02-11 20:40:52";
                "modified_at": "2017-02-11 20:40:52";
            }
### Edit KPI [PUT]

+ Request (application/json)

         {

                "title": "Number of Completed Tasks";
                "frequency": "Weekly";
                "format": "Number";
                "target": "3";
                "category_id": 1;
                "org_id": 1;
                "user_id": 23;
                "status": 1;
            }

+ Response 201 (application/json)

    + Headers

            Location: /kpi/:id

    + Body

            {
                "id": 2;
                "title": "Number of Completed Tasks";
                "frequency": "Weekly";
                "format": "Number";
                "target": "3";
                "category_id": 1;
                "org_id": 1;
                "user_id": 23;
                "status": 1;
                "created_at": "2017-02-11 20:40:52";
                "modified_at": "2017-02-11 20:40:52";
            }
### Remove KPI [DELETE]

+ Response 200 (application/json)

    + Body
    
            {
                "status": "Success";
                "message": "KPI was succesfully deleted";
            }